const DealsCombo = [
    {Dname:" Special Deal!",
     Ditems:"Meni Pedi + Hairstyle",
     Sname:"Cantt Area,Bahria Town",
     Price:"Rs.1000",
     oldPrice:"Rs.5000",
     
    },
    {Dname:" Christmas Deal!",
     Ditems:" MakeUp +Meni Pedi",
     Sname:"Main Area,Bahria Town",
     Price:"Rs9500",
     oldPrice:"Rs.15000",
    },
    {Dname:" New year Deal!",
     Ditems:"nail Art+Meni Pedi",
     Sname:"Gulberg Area,Model Town",
     Price:"Rs.8500",
     oldPrice:"Rs.10,000",
    },
    {Dname:" Special Deal!",
     Ditems:"Spa+Massage",
     Sname:"Ghumman Area,Nishter Town",
     Price:"Rs.7500",
     oldPrice:"Rs.8000",
    },   
    {Dname:" Special Deal!",
     Ditems:"Acne Treatment+ facial",
     Sname:"Central Park,Bahria Town",
     Price:"Rs.1500",
     oldPrice:"Rs.2500",
    },
    {Dname:" Premium Deal!",
     Ditems:"Hair treatment + Keratin",
     Sname:"Jinnah Park Area,Model Town",
     Price:"Rs.6500",
     oldPrice:"Rs.7900",
    },
    {Dname:" Special Deal!",
     Ditems:"Hydra Facial + Acne Treatment",
     Sname:"Medlay Area,Johar Town",
     Price:"Rs.3500",
     oldPrice:"Rs.4999",
    },
    {Dname:" Premium Deal!",
     Ditems:"Hair Style+ hair Cutting",
     Sname:"Shaheer MArket,Bahria Town",
     Price:"Rs.5500",
     oldPrice:"Rs.6700",
    },
    {
        Dname:" New year Deal!",
     Ditems:"Hair Cutting + Dressing",
     Sname:"Ambar Area,Bahria Town",
     Price:"Rs.4500",
     oldPrice:"Rs.5000",
    },
    {Dname:" Premium Deal!",
     Ditems:"hair Cutting+Meni Pedi",
     Sname:"Talwar Area,Bahria Town",
     Price:"Rs.3500",
     oldPrice:"Rs.5500",
    },
    {
     Dname:" New year Deal!",
     Ditems:"Makeup+Mehndi",
     Sname:"Noor Market,Model Town",
     Price:"Rs.2500",
     oldPrice:"Rs.3500",
    },
    {Dname:" Special Deal!",
     Ditems:"Facial + DarkSpot Treatment",
     Sname:"Central Park  Treatment,Bahria Town",
     Price:"Rs.1500",
     oldPrice:"Rs.3500",
    },
    {Dname:" New year Deal!",
     Ditems:"Facial+ Threading",
     Sname:"Central Park,Bahria Town",
     Price:"Rs.1500",
     oldPrice:"Rs.3500",
    },
    {Dname:" Special Deal!",
     Ditems:"Bridal Package+Mehndi",
     Sname:"Alan Area,Bahria Town",
     Price:"Rs.2500",
     oldPrice:"Rs.3500",
    },
    {Dname:" Premium Deal!",
     Ditems:"Keratin + Haircut",
     Sname:"Central Park,Bahria Town",
     Price:"Rs.1500",
     oldPrice:"Rs.2000",
    }
 ];
 
 export default DealsCombo;